### ISSUE TITLE
Cannot deploy to AWS - API: certificatemanager:changeResourceRecordSets is not authorized to access this resource

### ISSUE THREAD

**Issue by Vadorequest** [thabo-lebelo/on-demand-videos#3]
```
CDNStack (cdn): deploying...
cdn: creating CloudFormation changeset...
2:26:43 PM | CREATE_FAILED        | AWS::CertificateManager::Certificate            | cdnCertificate11AB9FE8
API: certificatemanager:changeResourceRecordSets User: arn:aws:sts::878228269602:assumed-role/tfp-admin-staging-car/aws-sdk-js-1661603145261 is not authorized to access this resource


 ❌  CDNStack (cdn) failed: Error: The stack named cdn failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: API: certificatemanager:changeResourceRecordSets User: arn:aws:sts::878228269602:assumed-role/tfp-admin-staging-car/aws-sdk-js-1661603145261 is not authorized to access this resource
    at prepareAndExecuteChangeSet (/Users/vadorequest/dev/unlyEd/template-init-aws-cloudfront-s3-cdn/node_modules/aws-cdk/lib/api/deploy-stack.ts:386:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at deployStack2 (/Users/vadorequest/dev/unlyEd/template-init-aws-cloudfront-s3-cdn/node_modules/aws-cdk/lib/cdk-toolkit.ts:240:24)
    at /Users/vadorequest/dev/unlyEd/template-init-aws-cloudfront-s3-cdn/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/Users/vadorequest/dev/unlyEd/template-init-aws-cloudfront-s3-cdn/node_modules/p-queue/dist/index.js:163:29)

```

I'm trying to deploy using a different profile (to deploy the stack to a particular AWS Account)

I'm getting this issue, and having trouble understanding where it comes from. Do I lack permission in AWS?

Here are my permissions.

![image](https://user-images.githubusercontent.com/3807458/187030558-db9140eb-6460-44ac-a9f1-e555dab0a618.png)

Would you mind sharing the permissions of the AWS IAM user/role you used to deploy?
Did you encounter a similar issue?

**Comment by Vadorequest** [comment]
I also tried using your version directly (not my own fork) and simply replace variables and I'm getting the same error.

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/3807458/187030839-fb6b8b95-4ded-4242-86c9-61a405814dcf.png">

**Comment by Vadorequest** [comment]
What is `"Id": "/hostedzone/Z0614066168C321XAWFXX"` ? It might come from that, I used my hostedZone ID but there were a few less chars than in your example.
